In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [7]:
print(x)

[['Indonesia' 32.0 72000.0]
 ['Malaysia' 27.0 48000.0]
 ['Singapore' 30.0 54000.0]
 ['Malaysia' 38.0 65000.0]
 ['Singapore' 40.0 nan]
 ['Indonesia' 35.0 58000.0]
 ['Malaysia' nan 52000.0]
 ['Indonesia' 48.0 79000.0]
 ['Singapore' 50.0 88000.0]
 ['Indonesia' 37.0 67000.0]]


In [8]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])


In [10]:
print(x)

[['Indonesia' 32.0 72000.0]
 ['Malaysia' 27.0 48000.0]
 ['Singapore' 30.0 54000.0]
 ['Malaysia' 38.0 65000.0]
 ['Singapore' 40.0 64777.77777777778]
 ['Indonesia' 35.0 58000.0]
 ['Malaysia' 37.44444444444444 52000.0]
 ['Indonesia' 48.0 79000.0]
 ['Singapore' 50.0 88000.0]
 ['Indonesia' 37.0 67000.0]]


In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [15]:
print(x)

[[1.0 0.0 0.0 32.0 72000.0]
 [0.0 1.0 0.0 27.0 48000.0]
 [0.0 0.0 1.0 30.0 54000.0]
 [0.0 1.0 0.0 38.0 65000.0]
 [0.0 0.0 1.0 40.0 64777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 1.0 0.0 37.44444444444444 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 50.0 88000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [17]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [19]:
print(x_train)

[[0.0 1.0 0.0 37.44444444444444 52000.0]
 [0.0 0.0 1.0 40.0 64777.77777777778]
 [1.0 0.0 0.0 32.0 72000.0]
 [0.0 1.0 0.0 38.0 65000.0]
 [0.0 1.0 0.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 50.0 88000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [20]:
print(x_test)

[[0.0 0.0 1.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [21]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [22]:
print(y_test)

[0 1]


In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:]= sc.fit_transform(x_train[:, 3:])
x_test[:, 3:]= sc.transform(x_test[:, 3:])

In [24]:
print(x_train)

[[0.0 1.0 0.0 -0.13727375902237984 -1.0967313724496195]
 [0.0 0.0 1.0 0.2184779545004064 -0.08470242294746261]
 [1.0 0.0 0.0 -0.8951795834839672 0.48731393981462573]
 [0.0 1.0 0.0 -0.059936429995687 -0.06710191947786014]
 [0.0 1.0 0.0 -1.5912155447242007 -1.4135404349024687]
 [1.0 0.0 0.0 1.3321354924847801 1.0417297991071115]
 [0.0 0.0 1.0 1.6105498769808735 1.754550189626022]
 [1.0 0.0 0.0 -0.4775580067398271 -0.621517778770346]]


In [25]:
print(x_test)

[[0.0 0.0 1.0 -1.1735939679800607 -0.9383268412231951]
 [1.0 0.0 0.0 -0.1991436222437337 0.0913026117485644]]


A11201911881 / Bambang Priyanto